### ISSUE TITLE
Adding param for download directory

### ISSUE THREAD

**Issue by LIQRGV** [sergeyklay/php-appveyor#15]
Just some advice, 
can we have some parameter to change the `$archive` parameter on https://github.com/sergeyklay/php-appveyor/blob/master/php-appveyor.psm1#L23?

**Comment by sergeyklay** [comment]
Yes, we can. Do you have any real proposal?

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
